project:
  type: book

book:
  title: "Causal inference notes"
  author: "Fabian Gunzinger"
  date: "8/3/2024"
  chapters:
    - index.qmd

    # Intro
    # - chapters/introduction.qmd
    # - chapters/history.qmd
    # - chapters/stats_for_business.qmd
    # - chapters/approaches_to_causal_inference.qmd

    # Statistics foundations
    - chapters/stats_foundations.qmd
    # - chapters/stats_details_like_lln_and_clt.qmd
    - chapters/projection.md
    # - chapters/fwl.qmd
    - chapters/regression.qmd

    # # Causal inference foundations
    # # - chapters/epistemology.qmd
    # - chapters/fundamental_problem.qmd
    - chapters/neyman_rubin_causal_model.qmd
    - chapters/fisher.qmd
    - chapters/neyman.md
    # - chapters/regression_for_experiments.qmd
    # # - chapters/sampling_vs_randomisation_uncertainty.qmd
    - chapters/experiment_stats.qmd
    - chapters/experiment_analysis.qmd
    # # - chapters/dags.qmd

    # Experiments in practice
    # - chapters/guiding_principles.qmd
    # - chapters/experiment_design.qmd
    # - chapters/experiment_stats.qmd
    - chapters/metrics.md
    # # - chapters/decision_making.qmd
    - chapters/power.qmd
    - chapters/threats_to_validity.qmd
    - chapters/practical_issues.qmd
    # - chapters/variance_reduction.qmd
    # # - chapters/cuped.qmd
    - chapters/network_experiments.qmd
    # - chapters/switchbacks.qmd
    # - chapters/heterogeneous_treatment_effects.qmd
    # - chapters/triggered_analysis.md


    # Quasi-experiments in practice
    # - chapters/quasi_experiments.qmd
    # - chapters/matching.qmd
    # - chapters/regression_discontinuity.qmd

    # Misc.
    # - chapters/multiple_hypothesis_correction.qmd
    # - chapters/misc_topics.qmd
    - chapters/ethics.qmd
    # - chapters/useful_resources.qmd
    # - chapters/references.qmd


bibliography: /Users/fgu/.dotfiles/latex/fabib.bib

format:
  html:
    theme: cosmo
    include-in-header: "math_commands.html"
  pdf:
    documentclass: scrreprt
    include-in-header: "math_commands.tex"
jupyter: python3
callout-icon: false




