project:
  type: book
  preview:
    browser: false

book:
  title: "Statistics and practice of online experiments"
  author: "Fabian Gunzinger"
  date: "2/12/2024"
  chapters:
    - index.qmd

    - part: "Introduction"
      chapters:
      - chapters/introduction.qmd

    - part: chapters/statistics.md
      chapters:
      - chapters/stats_of_online_experiments.md
      - chapters/outcomes.md
      - chapters/standard_error.md
      - chapters/testing_and_cis.md
      - chapters/power.md
      - chapters/analysis.md
      - chapters/threats_to_validity.qmd

      
    - part: chapters/practice.md
      chapters:
        # - chapters/important_topics.md
        # - chapters/guiding_principles.qmd
        # - chapters/ethics.qmd
        # - chapters/experiment_designs.md
        # - chapters/experiment_stats.qmd
        - chapters/metrics.md
        - chapters/experiment_configuration.md
        - chapters/decision_making.qmd
        # - chapters/threats_to_validity.qmd
        # - chapters/practical_issues.qmd
        # - chapters/variance_reduction.qmd
        # - chapters/network_experiments.qmd
        # - chapters/heterogeneous_treatment_effects.qmd
        # - chapters/long_term_effects.md
        # - chapters/triggered_analysis.md
        # - chapters/sequential_testing.md
        # - chapters/multiple_hypothesis_correction.qmd
        - chapters/multi_arm_bandits.md

    # - part: "Experiment platforms"
    #   chapter:
    #     - chapters/platform_architecture_at_jet.md

    # - part: "Quasi-experiments"
    #   chapters:
    #     - chapters/quasi_experiments.qmd
    #     - chapters/matching.qmd
    #     - chapters/regression_discontinuity.qmd


    - part: "Appendices"
      chapters:
        - chapters/assignment_mechanism.md
        - chapters/notes_on_athey2017econometrics.md
      # - chapters/stats_foundations.qmd
      # - chapters/projection.md
      # - chapters/fwl.qmd
      # - chapters/stats_details_like_lln_and_clt.qmd

      # - chapters/regression.qmd
      # - chapters/regression_for_experiments.qmd
      
      # - chapters/fisher.qmd
      # - chapters/neyman.md
      # - chapters/treatment_effects.md

      # - chapters/history.qmd
      # - chapters/alternative_approaches.qmd
      # - chapters/useful_resources.qmd
      # - chapters/references.qmd

bibliography: /Users/fgunzinger/.dotfiles/latex/fabib.bib


# format:
#   html:
#     theme: cosmo
#     include-in-header: "math_commands.html"
#   pdf:
#     documentclass: scrreprt
#     include-in-header: "math_commands.tex"
# jupyter: python3
# callout-icon: false




