project:
  type: book

book:
  title: "Online experiments"
  author: "Fabian Gunzinger"
  date: "8/3/2024"
  chapters:
    - index.qmd

    - part: "Introduction"
      chapters:
      - chapters/introduction.qmd
      # - chapters/history.qmd
      # - chapters/stats_for_business.qmd
      # - chapters/approaches_to_causal_inference.qmd
      # - chapters/epistemology.qmd
      # - chapters/fundamental_problem.qmd

    - part: chapters/statistics.md
      chapters:
      # - chapters/fisher.qmd
      # - chapters/neyman.md
      # - chapters/sampling_vs_randomisation_uncertainty.qmd
      - chapters/treatment_assignment.md
      - chapters/outcomes.md
      - chapters/standard_error.md
      - chapters/testing_and_cis.md
      - chapters/power.md
      - chapters/analysis.md
      - chapters/super_population.md
      # - chapters/regression.qmd
      # - chapters/regression_for_experiments.qmd
    
    - part: "Practical issues"
      chapters:
        - chapters/guiding_principles.qmd
        - chapters/ethics.qmd
        - chapters/experiment_design.md
        # - chapters/experiment_stats.qmd
        - chapters/metrics.md
        - chapters/decision_making.qmd
        - chapters/threats_to_validity.qmd
        - chapters/practical_issues.qmd
        - chapters/variance_reduction.qmd
        - chapters/network_experiments.qmd
        - chapters/heterogeneous_treatment_effects.qmd
        - chapters/long_term_effects.md
        - chapters/triggered_analysis.md
        - chapters/multiple_hypothesis_correction.qmd

    - part: "Quasi-experiments"
      chapters:
        - chapters/quasi_experiments.qmd
        - chapters/matching.qmd
        - chapters/regression_discontinuity.qmd


    - part: "Appendices"
      chapters:
      - chapters/stats_foundations.qmd
      # - chapters/stats_details_like_lln_and_clt.qmd
      - chapters/projection.md
      - chapters/fwl.qmd
      # - chapters/dags.qmd


      # Misc.
      # - chapters/treatment_effects.md
      # - chapters/misc_topics.qmd
      # - chapters/useful_resources.qmd
      # - chapters/references.qmd


# bibliography: /Users/fgu/.dotfiles/latex/fabib.bib
bibliography: /Users/fabian.gunzinger/.dotfiles/latex/fabib.bib

format:
  html:
    theme: cosmo
    include-in-header: "math_commands.html"
  pdf:
    documentclass: scrreprt
    include-in-header: "math_commands.tex"
jupyter: python3
callout-icon: false




