project:
  type: book

book:
  title: "Online Experiments"
  author: "Fabian Gunzinger"
  date: "9/28/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: introduction.qmd
      chapters:
        - epistemology.qmd
        - ethics.qmd
        - fundamental_problem.qmd
        - potential_outcomes.qmd
        - dags.qmd
        - statistics.qmd
    - part: experiments.qmd
      chapters:
        - practical_issues.qmd
    - part: quasi_experiments.qmd
      chapters:
        - matching.qmd
        - regression_discontinuity.qmd
    - summary.qmd
    - useful_resources.qmd
    - references.qmd

bibliography: fabib.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



