#!/bin/bash

# Define the path of your files
project_path="/Users/fgu/dev/personal/causal-inference-notes"
tex_file_path="$project_path/math_commands.tex"
html_file_path="$project_path/math_commands.html"

# Start the HTML file
echo '<span class="math inline">' > "$html_file_path"
echo '    \(' >> "$html_file_path"

# Copy lines from tex to html files
while IFS= read -r line
do
  echo "    ${line}" >> "$html_file_path"
done < "$tex_file_path"

# Close the HTML tag
echo '    \)' >> "$html_file_path"
echo '</span>' >> "$html_file_path"

