# Statistics of online experiments

Our estimate of the average treatment effect is

$$
\hat{\tau} = \bar{Y}^{obs}_t - \bar{Y}^{obs}_c,
$$

where

$$
\bar{Y}_t^{obs} = \frac{1}{N_t}\sum_{i:W_i=1} Y_i^{obs} \qquad \bar{Y}_c^{obs} = \frac{1}{N_c}\sum_{i:W_i=0} Y_i^{obs}.
$$

This is an unbiased estimate of $\tau = \bar{Y(1)} - \bar{Y(0)}$ (see Proof of Theorem 6.1 in @imbens2015causal).

Because treatment and control units are independently and randomly assigned, an unbiased estimate of the sampling variance of $\hat{\tau}$ is given by[^vardetails]:

$$
Var(\hat{\tau}) = \frac{s^2_t}{N_t} + \frac{s^2_c}{N_c},
$$

where

$$
s_c^2 = \frac{1}{N_c - 1}\sum_{i:W_i=0}\left(Y_i(0) - \bar{Y}_c^{obs}\right)^2 \qquad s_t^2 = \frac{1}{N_t - 1}\sum_{i:W_i=1}\left(Y_i(1) - \bar{Y}_t^{obs}\right)^2.
$$

To test whether the observed treatment effect is significantly different from zero, we test:

$$
H_0: \bar{Y}^{obs}_t = \bar{Y}^{obs}_c
H_A: \bar{Y}^{obs}_t \neq \bar{Y}^{obs}_c.
$$

We calculate the test-statistic

$$
T = \frac{\hat{\tau}}{\sqrt{Var(\hat{\tau})}} \sim t_{(N_t + N_c - 2)},
$$

where $N_t + N_c - 2$ is number of degrees of freedom[^tdetails].

todo:

- See Rice 6.2 on why this follows t distribution
- For complete treatment and derivation of sampling distributions (incl. discussion of all the approximations and sample corrections), see Rice sampling chapter and my ipad notes.



[^vardetails] We gloss over a few details here. Depending on the treatment assignment mechanism, units are not independently assigned. In online experiments, we often use hash functions for treatment assignment, in which case assignment is independent. But if we use the assignment mechanism of a completely randomised experiment, where we perfectly balance the number of units assigned to each treatment, each unit being assigned to one variant lowers the probability of all other units being assigned to that same variant. In that case, the above variance estimator is unbiased only if the treatment effect is constant. However, it is usually used in practice even in cases where constant treatment effects are unlikely because it is conservative (i.e. at least as large as the true variance) and because it is always unbiased if the ATE is an estimate of the infinite super-population ATE.

[^tdetails] Note that the test statistic follows a t-distribution because we have to estimate the variance (that is, if we replace the true variance with its estimate when standardising a normal variable, the result follows a Student's t-distribution). So, this has nothing to do with the CLT. However, for the test statistic to follow a student distribution, the numerator has to follow a normal distribution. Often, though, the underlying data is not normal, so that its approximately normal only for large enough samples, due to the CLT. At the same time, the t-distribution also converges to normal as the sample size increases. Hence, one we have a sample size large enough to justify using the t-distribution, we might as well use a z-test. As pointed out in Chapter 9 in @rice2006mathematical, the test statistic above only follows a t-distribution if we use the pooled variance, but for large sample sizes, the distribution is still approximately t or normal.


