# Introduction


## Why causal inference?

- Because many thinks we think work don't (look at list of refuted claims from Kohavi [here](https://experimentguide.com/refuted_observational_studies/))

The purpose:

- Create a valid counterfactual outcome - the outcome of the treated if they had not been treated - in order to eliminate selection bias when estimating the treatment effect.


## Why experiments

1. The randomisation of treatment eliminates selection bias.

2. The presence of a control group provides a counterfactual of what would have happened without treatment.

## Fundamental problem of causal inference


## Limitations of experiments

Look at Deaton and Cartwright papers.

1) They cannot be used to study the past.

2) They can only estimate the effect of treatments that can be manipulated ("no causation without manipulation" Rubin). 

3) Guidance for policy limited by compliance issues, environmental dependence, and equilibrium effects.

4) There are ethical concerns.

- For deeper discussion, see @stevenson2024cause and sources therein.



## Thinking about causality


- [Milton Friedman thermostat example](https://www.mercatus.org/macro-musings/nick-rowe-monetary-basics-milton-friedmans-thermostat-and-more)

## Interpretation

- We often think of experiment as answering: "Does the intervention work?", but what it really answers is "What is the average effect of the intervention with this specific implementation for this particular population at this time?"

- When we have multiple treatments or analyse subgroups separately, we need to test whether different estimates are significantly different from each other (can't just look at whether some are significantly different from zero while some aren't) 


## Description vs prediction vs causal inference

- Descriptive analysis describes the data. We simply turn data into meaningfull summary measures presented in tables or -- better, usually! -- figures. The aim here is to simply describe the data as it is, highlighting aspects that are particularly interesting or relevant to the task at hand.

- Predictive analysis predicts unobserved metric values based on observed ones. We build a model that captures the data generating process of the metric we aim to predict based on training data we observe, so that we can then predict metric values we don't observe.

- Causal inference makes statements about what would happen to outcomes if we changed the world in a particular way.

Causal inference vs prediction

- Prediction is about finding the most likely outcome based on a set of (existing) covariates. Causal inference is about finding the effect of a change in a covariate on the outcome.

- The difference is profound: when predicting, you take the features as a given and predict outcomes based on them -- you're asking: "given existing features, what outcome can I expect?". When you perform causal inference, you want to know what would happen if you were to change one of the covariates -- you're asking "if I were to change one covariate in a certain way, what outcome could I expect?".

- Causal inference is about manipulating covariates -- to paraphrase Donald Rubin: there is no causality without manipulation.

- Technically, what this really comes down to is that in prediction, you don't care about selection bias, whereas in causal inference that's the main thing you care about.

- This also means that the role of goodness of fit is very different: for prediction, it's obviously very important -- if your model explains only a very small part of the variation in the outcome, it won't be very good at predicting outcomes. In causal inference, goodness of fit doesn't matter because your aim is not to predict, but to know how the outcome changes if you change a covariate. So, you can have very low goodness of fit (lots of things outside the model predicting outcomes), but if you can precisely estimate your treatment effect, that's very valuable (you learn that regardless of all the many other factors that determine the outcome, changing a covariate in a certain way tends to change outcomes in a certain way.)