# Matching

## Description

- Preprocess observational data such that it resembles more closely data that would have resulted from a perfectly blocked (and possibly randomised) experiment, and thus break the relationship between outcomes and pre-treatment controls.

- Overall goal is to create a dataset that mimics data from a randomised experiment as closely as possibe. Hence, to create data where treatment and control groups are as similar as possible on all observable covariates so that the only difference between them is the treatment.

- As described in @stuart2010matching, a matching anaysis has two stages.

- Design stage (with matching in mind, but holds more generally for synthetic control, regression discontinuity, diff in diff):
    - Define "similarity" between treatment and control group
    - Select similar control group based on above definition
    - Validate similarity between treatment and control

- Analysis stage
    - Analyse the data

## Assumptions

## Data requirement

## Comparison group

## Considerations

- Balance checks: successful matching removes the relationship between outcomes and pre-treatment controls that's often inherent in non-experimental data. To check whetehr this succeeded, we need to check that the distribution of pre-treatment controls is the same within matched treatment and control units.

- Analysis: using difference in mean test is only appropriate if we performed exact matching, which is often not feasible. For all other forms of matching, use model with controls to estimate treatment effects.

## Examples

- Opportunity sizing making field mandatory

## Software

- @stuart2011matchit


## Matching vs synthetic controls vs regression

- Based on excellent discussion in introduction to @abadie2021penalized.

- Synthetic control vs nearest-neighbour matching:

  - Similarities: Weights for control units are positive, sum to one, and are often sparse. This allows for interpretability of the weights.

  - Differences: synthetic control doesn't impose a fixed number of control units, and, instead of using a simple average of the control units with equal weights, it creates a control unit using a weighted average of all control units such as to minimise the discrepancy between treated and control units in the values of the matching variables.


