# Neyman-Rubin causal model

## Potential outcomes

## Causal estimands

- We have a population of units $i = 1, \dots, N$.

- Each unit in the population can be exposed to one of two treatments, which are identical across units, so that $\mathbb{T}_i = \mathbb{T} = \{0, 1\}$.

- Each unit $i$ has potential outcomes $Y_i(0)$ and $Y_i(1)$ corresponding to each of the two possible treatments.

- Unit-level causal effects are given by comparisons of $Y_i(0)$ and $Y_i(1)$, often expressed as a simple difference:

$$
Y_i(1) - Y_i(0).
$$

- We often want to summarise unit-level treatment effects, to which effect we can calculate many different causal estimands.

- The average treatment effect over the entire population (the finite sample) is defined as:

$$
\tau_{fs} = \frac{1}{N}\sum_{i=1}^N \left(Y_i(1) - Y_i(0)\right).
$$

- Hence: the causal effect is the average difference in individual potential outcomes.

- We can generalise this in a number of ways.

- We can focus only on a subset of the population, which can also happen in different ways.

- We can condition on covariates, such as when we focus only on women:
$$
\tau_{fs, f} = \frac{1}{N_f}\sum_{i: X_i = f} \left(Y_i(1) - Y_i(0)\right), \quad \text{where $X_i = \{m , f\}$ and $N_f = \sum_{i=1}^N \mathbb{1}_{X_i = f}$}
$$

- We can condition on treatment status, such as when we focus only on units that were exposed to the treatment: 

$$
\tau_{fs, t} = \frac{1}{N_t}\sum_{i: W_i = 1} \left(Y_i(1) - Y_i(0)\right), \quad \text{where $W_i = \{0 , 1\}$ and $N_t = \sum_{i=1}^N \mathbb{1}_{W_i = 1}$}
$$

- We can condition on potential outcomes, such as when we focus only on units with positive potential outcomes (e.g. positive earnings) regardless of treatment status:

$$
\tau_{fs, pos} = \frac{1}{N_{pos}}\sum_{i: Y_i(0)>0, Y_i(1)>0} \left(Y_i(1) - Y_i(0)\right), \quad \text{where $N_{post} = \sum_{i=1}^N \mathbb{1}_{Y_i(0)>0, Y_i(1)>0}$}
$$

- We can also generalise the estimand by focusing on more general functions of the potential outcomes (e.g. we may focus on the median outcome of the entire population or a subpopulation).

- In all these cases, we can write the causal estimand as a row-exchangeable function (a function that takes vectors or matrices as arguments and the result of which does not change if the rows in its input are permuted):

$$
\tau = \tau(Y(0), Y(1), X, W)
$$



## Stable unit treatment value assumption (SUTVA)

- SUTVA has two components: no interference, and no hidden variations of treatments.

 **No interference**

- The no interference assumption states that a unit's potential outcumes are independent of the treatment assignment of all other units.

- This will be violated if there are network effects: if the behaviour of units is mutually dependent. For instance: if my wife and I both use an online photo-sharing service and my wife sees a new feature that we both like while I'm in the control group, we might stil share the same number of family photos but start sharing them all on her account instead of mine. This creates an artificial treatment effect because if I had also had access to the new feature, we might not have changed our behaviour at all, while, during the experiment, her sharing volume went up while mine went down, suggesting the existent of a positive effect.

- Another case where the no interference assumption can be violated is in the form of general equilibrium effects. A classic example is the effect of further education: the effect of my doing a PhD in statistics on my earnings while nobody else changes their behaviour (the partial-equilibrium effect) is surely different from the outcome of my earnings if suddenly everyone decided to do a PhD in statistics (the general-equilibrium effect).

- The two violations capture the two different ways interference can lead to incorrect results: interference can happen and bias our results either during the experiment or once the feature is fully rolled out. In either case, the treatment of some unit has an externality on other units.

**No hidden treatment variations**

- The second component, no hidden treatment variation, states that a unit receiving a specific treatment level cannot receive different forms of that treatment level. This does *not* mean that the form of the treatment level has to be the same for each unit, but only that a given treatment level is well specified for a given unit. To use Imbens and Rubin's aspirin example: suppose we test the effect of aspirin on reducing headaches but have old and new aspirins which vary in strength, so that we effectively have three possible treatment statuses: no aspirin (control), weak aspirin, and strong aspirin. SUTVA does *not* require that all treatment units either get the weak or the strong aspirin, but requires that each unit can only receive one or the other in case they are treated, so that there is no ambiguity what form of the treatment a given unit will receive in case it is treated. (It would be permissible to have the treatment be randomly weak or strong, but this is not relevant in my world.)

- Essentially, both parts of SUTVA ensure the same thing: that $Y_i(w)$ is well defined: that it does not depend on the treatment status of other units, and that, for each possible treatment level, $w$, the precise form of that treatment level is well specified.


## Finite sample vs super-population perspective

There are two ways to perform inference:

- When using the finite sample perspective, the $N$ units in the experiment sample are treated as the entire population of interest. Hence, there is no notion of randomisation due to sampling from a larger population, and all the randomness in the outcomes is due to randomness generates by the assignment mechanism.

- When treating the $N$ units in the sample as a random sample from a larger super-population, then in addition to randomness from the randomisation, we also have randomness from the sampling.



## How does randomisation help us estimate ATEs?

By ensuring that the treatment - the causal variable of interest - is independent of potential outcomes, so that control and treatment group are comparable.

More technically, it ensures that expected outcomes are the same in both groups, which means that the selection bias - the difference of expected potential outcomes without treatment - disappears. When using regression, this is equivalent to the error term being uncorrelated with treatment status.



## Useful resources


