# Stats for business

- In some business organisations there is a prevailing wisdom that "science" often in the form of A/B testing (which is the digital version of controlled experiments) makes making decisions harder by slowing them down, which wastes important time.

- One of the main jobs of an experimentation specialist in an organisation is to help people understand why running experiments is crucial. In this space, I want to gather my evolving thoughts on this topic with the aim of crafting an increasingly convincing argument.

Relevant thoughts:

- Epistemic argument about how we know what works: human behaviour is heterogeneous and largely unpredictable, so to know what works you need to test things, and the easiest (certainly for most tech companies) and most rigorous way to test things is to run experiments.

- Experiments do not slow decision making down, but are one of the most powerful tools we have to ensure that the decisions we make are good ones.

- Discuss when not to experiment (for there clearly are cases where you either don't have the time or where there really is no need).

- Andrew Gelman argues (in [this](https://statmodeling.stat.columbia.edu/2023/11/24/what-are-the-important-parts-of-statistics/) blog post) that i) "to reduce, control, or adjust for bias and variation in measurements" and ii) "to systematically gather data on multiple cases" are the two most important parts of statistics. This is a good way of emphasising why running experiments in a standardised way are important even if you feel you have data about your feature: it ensures that you collect data from a representative sample of users and it ensures you are judging the success of your feature by pre-defined metrics defined in a standardised way (at least ideally!).

- How do we define identity of executives or product managers: not around knowing what is true or what works or what customers want, but around coming up with good hypotheses, being willing to learn from data, and strong at iterating on features based on data and past experience.

Is experimentation worth it?

- @king2020power on how Pinterest was able to build a machine-learning system that is 20% better at detecting policy-violating content thanks to incremental testing that experimentation allows.

