# Switchback experiments

- Also called time-series experiments.


## Notes on @bojinov2023design

- AB tests have two main challenges in practice: dealing with interaction effects, and estimating heterogeneous treatment effects.

- Switchback experiments sequentially assign units to a random treatment, measure the response, and repeat the proceedure for a fixed period of time.

- The approach can thus deal with both limitations above: it limits interference, and it can estimate individual-level causal effects, thus providing the ability to estiamte heterogeneous treatment effects.

- Instead of making assumptions on the outcome model under interference, switchback experiments require assumptions on the duration of carryover effects, the duration for which the effects of one treatment during a particular period affects outcomes in subsequent periods (the authors call this carryover duration the "order of carryover effects").

- There are two main areas of application: to deal with interference in a network (either in the context of [network or marketplace interference](network_experiments.qmd## Types of interferance)) and to deal with situations where we have a limited number of units in the experiment and where we expect heterogeneous treatment effects.

- There are three main challenges when running switchback experiments:

    1. ATE estimators from switchback experiments have high variance because the precision is a function of the total number of assignments.

    2. One has to deal with the existence of carryover effects.

    3. Super-population inference requires unrealistic assumptions.

- The paper provides solutions for all of them:

    1. It provides an optimal design approach that reduces variance

    2. It assumes carryover effects and shows that estimation and inference is valid both when they are correctly and incorrectly specified, though in the latter case estimation variance is higher. The authors also provide a method for practitioners to measure the duraton of carryover effects.

    3. It takes a purely design-based perspective on inference by assuming that outcomes are unknown but fixed, which means that findings are wholy non-parametric and robust to model misspecification (akin to the approach of [Fisher's exact P-value approach](fisher.qmd))

- Assumptions:

**Assumption 1 (Non-anticipating Potential Outcomes).** 

For any $t \in [T]$, $w_{1:t} \in \{0,1\}^t$, and for any $w', w'' \in \{0,1\}^{T-t}$,
$$ Y_t(w_{1:t}, w'_{t+1:T}) = Y_t(w_{1:t}, w''_{t+1:T})$$

- This says that potential outcomes don't depend on future assignments. Given that we control the assignment mechanisms, this holds by design (i.e. units can't adapt their behaviour in a given period based on future assignments because these assignments are random).

**Assumption 2 (m-Carryover Effects).** 

There exists a fixed and given m, such that for any $t \in \{m+1, m+2, \ldots, T\}$, $w \in \{0,1\}^{T-t+m+1}$, and for any $w', w'' \in \{0,1\}^{t-m-1}$,
$$ Y_t(w'_{1:t-m-1}, w_{t-m:T}) = Y_t(w''_{1:t-m-1}, w{t-m:T})$$

- This says that outcomes at time $t$ are independent of assignenments more than $m$ periods in the past.

- Together, the two assumption imply that for any $t \in \{m + 1, \ldots, T\}$ and any two assignment paths $w, w' \in \{0, 1\}^{m+1}$, whenever $w = w'$ this leads to:

$$
Y_t(w_{1:T})=Y_t(w'_{1:T})
$$

- Which is a rigorous way of waying that all that matters do determine potential outcomes at time $t$ is the assignment history of the previous $m$ periods.









## Useful resources

- @bojinov2023design

- @bojinov2019time

- [Experiment Rigor for Switchback Experiment Analysis](https://doordash.engineering/2019/02/20/experiment-rigor-for-switchback-experiment-analysis/)

- [Analyzing Switchback Experiments by Cluster Robust Standard Error to Prevent False Positive Results](https://doordash.engineering/2019/09/11/cluster-robust-standard-error-in-switchback-experiments/)